import { KPIStat8Props } from "@/components/charts/kpi_stat_8";
import { KPIStat9Props } from "./components/charts/kpi_stat_9";
import { KPIStat7Props } from "./components/charts/kpi_stat_7";
import { Gauge, Clock, PieChart, Globe, MousePointer, Server } from "lucide-react";

export const kpiStat9: KPIStat9Props[] = [
    {
        title: "S&P 500",
        subtitle: "Standard & Poor's 500",
        value: "$5,969.51",
        chartData: [
            { month: "January", value: 4850 },
            { month: "February", value: 4790 },
            { month: "March", value: 4920 },
            { month: "April", value: 4880 },
            { month: "May", value: 4950 },
            { month: "June", value: 4890 },
            { month: "July", value: 4970 },
            { month: "August", value: 4920 },
            { month: "September", value: 5010 },
            { month: "October", value: 4980 },
            { month: "November", value: 5100 },
        ],
        change: "1.2%",
        color: "success",
        xaxis: "month",
    },
    {
        title: "ABNB",
        subtitle: "Airbnb, Inc.",
        value: "$137,34",
        chartData: [
            { month: "January", value: 120 },
            { month: "February", value: 126 },
            { month: "March", value: 123 },
            { month: "April", value: 130 },
            { month: "May", value: 133 },
            { month: "June", value: 128 },
            { month: "July", value: 125 },
            { month: "August", value: 132 },
            { month: "September", value: 135 },
            { month: "October", value: 134 },
            { month: "November", value: 136 },
        ],
        change: "0.3%",
        color: "warning",
        xaxis: "month",
    },
    {
        title: "UBER",
        subtitle: "Uber Technologies, Inc.",
        value: "$71,51",
        chartData: [
            { month: "January", value: 85 },
            { month: "February", value: 82 },
            { month: "March", value: 79 },
            { month: "April", value: 77 },
            { month: "May", value: 75 },
            { month: "June", value: 74 },
            { month: "July", value: 73 },
            { month: "August", value: 72 },
            { month: "September", value: 71 },
            { month: "October", value: 70 },
            { month: "November", value: 69 },
            { month: "December", value: 71 },
        ],
        change: "-0.8%",
        color: "danger",
        xaxis: "month",
    },
    {
        title: "BTC",
        subtitle: "Bitcoin (USD)",
        value: "$97,859",
        chartData: [
            { month: "January", value: 42582 },
            { month: "February", value: 61198 },
            { month: "March", value: 71333 },
            { month: "April", value: 60636 },
            { month: "May", value: 67491 },
            { month: "June", value: 62678 },
            { month: "July", value: 64619 },
            { month: "August", value: 58969 },
            { month: "September", value: 63329 },
            { month: "October", value: 70215 },
            { month: "November", value: 97850 },
        ],
        change: "10.9%",
        color: "secondary",
        xaxis: "month",
    },
    {
        title: "AAPL",
        subtitle: "Apple Inc.",
        value: "$172.62",
        chartData: [
            { month: "January", value: 185 },
            { month: "February", value: 182 },
            { month: "March", value: 178 },
            { month: "April", value: 169 },
            { month: "May", value: 173 },
            { month: "June", value: 175 },
            { month: "July", value: 178 },
            { month: "August", value: 176 },
            { month: "September", value: 171 },
            { month: "October", value: 170 },
            { month: "November", value: 173 },
        ],
        change: "0.5%",
        color: "primary",
        xaxis: "month",
    },
    {
        title: "GOOG",
        subtitle: "Alphabet Inc.",
        value: "$166,57",
        chartData: [
            { month: "January", value: 150 },
            { month: "February", value: 155 },
            { month: "March", value: 158 },
            { month: "April", value: 162 },
            { month: "May", value: 160 },
            { month: "June", value: 163 },
            { month: "July", value: 165 },
            { month: "August", value: 164 },
            { month: "September", value: 166 },
            { month: "October", value: 165 },
            { month: "November", value: 167 },
        ],
        change: "0.2%",
        color: "default",
        xaxis: "month",
    },
];

export const kpiStat8: KPIStat8Props[] = [
    {
        title: "Bounce Rate",
        value: "42.3%",
        chartData: [
            { month: "January", value: 18.2 },
            { month: "February", value: 22.1 },
            { month: "March", value: 37.8 },
            { month: "April", value: 53.5 },
            { month: "May", value: 65.8 },
            { month: "June", value: 71.2 },
            { month: "July", value: 62.8 },
            { month: "August", value: 52.3 },
            { month: "September", value: 51.8 },
            { month: "October", value: 50.3 },
            { month: "November", value: 51.1 },
            { month: "December", value: 40.5 },
        ],
        icon: Gauge,
        change: "-5.9%",
        color: "default",
        xaxis: "month",
    },
    {
        title: "Avg. Session Duration",
        value: "4:32",
        chartData: [
            { month: "January", value: 205 },
            { month: "February", value: 185 },
            { month: "March", value: 242 },
            { month: "April", value: 228 },
            { month: "May", value: 265 },
            { month: "June", value: 245 },
            { month: "July", value: 262 },
            { month: "August", value: 272 },
            { month: "September", value: 268 },
            { month: "October", value: 255 },
            { month: "November", value: 260 },
            { month: "December", value: 258 },
        ],
        icon: Clock,
        change: "+12.4%",
        color: "success",
        xaxis: "month",
    },
    {
        title: "Conversion Rate",
        value: "3.8%",
        chartData: [
            { month: "January", value: 2.1 },
            { month: "February", value: 2.4 },
            { month: "March", value: 3.2 },
            { month: "April", value: 2.8 },
            { month: "May", value: 3.5 },
            { month: "June", value: 3.2 },
            { month: "July", value: 3.6 },
            { month: "August", value: 3.8 },
        ],
        change: "+1.7%",
        color: "warning",
        icon: PieChart,
        xaxis: "month",
    },
    {
        title: "Pages per Session",
        value: 4.2,
        chartData: [
            { month: "Monday", value: 3.8 },
            { month: "Tuesday", value: 4.5 },
            { month: "Wednesday", value: 4.1 },
            { month: "Thursday", value: 3.9 },
            { month: "Friday", value: 4.3 },
            { month: "Saturday", value: 4.0 },
            { month: "Sunday", value: 4.2 },
        ],
        change: "+4.20",
        color: "primary",
        icon: Globe,
        xaxis: "day",
    },
    {
        title: "New vs Returning",
        value: "48.5%",
        chartData: [
            { month: "January", value: 72.4 },
            { month: "February", value: 74.2 },
            { month: "March", value: 71.5 },
            { month: "April", value: 69.8 },
            { month: "May", value: 70.1 },
            { month: "June", value: 68.9 },
            { month: "July", value: 67.8 },
            { month: "August", value: 68.5 },
        ],
        change: "-12.9%",
        color: "secondary",
        icon: MousePointer,
        xaxis: "month",
    },
    {
        title: "Load Time (ms)",
        value: "856ms",
        chartData: [
            { month: "January", value: 200 },
            { month: "February", value: 380 },
            { month: "March", value: 250 },
            { month: "April", value: 390 },
            { month: "May", value: 420 },
            { month: "June", value: 485 },
            { month: "July", value: 520 },
            { month: "August", value: 516 },
        ],
        change: "-28.7%",
        color: "danger",
        icon: Server,
        xaxis: "month",
    },
];



export const kpiStat7: KPIStat7Props[] = [
    {
        title: "Total Revenue",
        value: "$228k",
        change: "3%",
        changeType: "positive",
        trendChipPosition: "bottom",
        chartData: [
            { weekday: "Mo", value: 13200 },
            { weekday: "Tu", value: 8800 },
            { weekday: "We", value: 9441 },
            { weekday: "Th", value: 12300 },
            { weekday: "Fr", value: 16400 },
            { weekday: "Sa", value: 14000 },
            { weekday: "Su", value: 11300 },
        ],
    },
    {
        title: "Total Expenses",
        value: "$71.2k",
        change: "1%",
        changeType: "neutral",
        trendChipPosition: "bottom",
        chartData: [
            { weekday: "Mo", value: 5000 },
            { weekday: "Tu", value: 6200 },
            { weekday: "We", value: 9800 },
            { weekday: "Th", value: 5300 },
            { weekday: "Fr", value: 5700 },
            { weekday: "Sa", value: 6400 },
            { weekday: "Su", value: 8187 },
        ],
    },
    {
        title: "Total Profit",
        value: "$156k",
        change: "8%",
        changeType: "negative",
        trendChipPosition: "bottom",
        chartData: [
            { weekday: "Mo", value: 11500 },
            { weekday: "Tu", value: 7000 },
            { weekday: "We", value: 7641 },
            { weekday: "Th", value: 12700 },
            { weekday: "Fr", value: 13300 },
            { weekday: "Sa", value: 15600 },
            { weekday: "Su", value: 11813 },
        ],
    },
];