import { KPIStat9Props } from "@/components/charts/kpi_stat_9";
import { KPIStat8Props } from "@/components/charts/kpi_stat_8";
import { KPIStat7Props } from "@/components/charts/kpi_stat_7";
import { KPIStat6Props } from "@/components/charts/kpi_stat_6";
import { KPIStat5Props } from "@/components/charts/kpi_stat_5";
import { KPIStat4Props } from "@/components/charts/kpi_stat_4";
import { Graph1Props } from "@/components/charts/graph_1";
import { Graph2Props } from "@/components/charts/graph_2";
import { Circles4Props } from "@/components/charts/circles_4";
import { Bars1Props } from "@/components/charts/bars_1";
import { Bars2Props } from "@/components/charts/bars_2";
import { Bars3Props } from "@/components/charts/bars_3";
import { Bars4Props } from "@/components/charts/bars_4";
import { Circles1Props } from "@/components/charts/circles_1";
import { Circles2Props } from "@/components/charts/circles_2";
import { Gauge, Clock, PieChart, Globe, MousePointer, Server, Home, Laptop, Palmtree, Bike } from "lucide-react";

export const kpiStat9: KPIStat9Props[] = [
    {
        title: "S&P 500",
        subtitle: "Standard & Poor's 500",
        value: "$5,969.51",
        chartData: [
            { month: "January", value: 4850 },
            { month: "February", value: 4790 },
            { month: "March", value: 4920 },
            { month: "April", value: 4880 },
            { month: "May", value: 4950 },
            { month: "June", value: 4890 },
            { month: "July", value: 4970 },
            { month: "August", value: 4920 },
            { month: "September", value: 5010 },
            { month: "October", value: 4980 },
            { month: "November", value: 5100 },
        ],
        change: "1.2%",
        color: "success",
        xaxis: "month",
    },
    {
        title: "ABNB",
        subtitle: "Airbnb, Inc.",
        value: "$137,34",
        chartData: [
            { month: "January", value: 120 },
            { month: "February", value: 126 },
            { month: "March", value: 123 },
            { month: "April", value: 130 },
            { month: "May", value: 133 },
            { month: "June", value: 128 },
            { month: "July", value: 125 },
            { month: "August", value: 132 },
            { month: "September", value: 135 },
            { month: "October", value: 134 },
            { month: "November", value: 136 },
        ],
        change: "0.3%",
        color: "warning",
        xaxis: "month",
    },
    {
        title: "UBER",
        subtitle: "Uber Technologies, Inc.",
        value: "$71,51",
        chartData: [
            { month: "January", value: 85 },
            { month: "February", value: 82 },
            { month: "March", value: 79 },
            { month: "April", value: 77 },
            { month: "May", value: 75 },
            { month: "June", value: 74 },
            { month: "July", value: 73 },
            { month: "August", value: 72 },
            { month: "September", value: 71 },
            { month: "October", value: 70 },
            { month: "November", value: 69 },
            { month: "December", value: 71 },
        ],
        change: "-0.8%",
        color: "danger",
        xaxis: "month",
    },
    {
        title: "BTC",
        subtitle: "Bitcoin (USD)",
        value: "$97,859",
        chartData: [
            { month: "January", value: 42582 },
            { month: "February", value: 61198 },
            { month: "March", value: 71333 },
            { month: "April", value: 60636 },
            { month: "May", value: 67491 },
            { month: "June", value: 62678 },
            { month: "July", value: 64619 },
            { month: "August", value: 58969 },
            { month: "September", value: 63329 },
            { month: "October", value: 70215 },
            { month: "November", value: 97850 },
        ],
        change: "10.9%",
        color: "secondary",
        xaxis: "month",
    },
    {
        title: "AAPL",
        subtitle: "Apple Inc.",
        value: "$172.62",
        chartData: [
            { month: "January", value: 185 },
            { month: "February", value: 182 },
            { month: "March", value: 178 },
            { month: "April", value: 169 },
            { month: "May", value: 173 },
            { month: "June", value: 175 },
            { month: "July", value: 178 },
            { month: "August", value: 176 },
            { month: "September", value: 171 },
            { month: "October", value: 170 },
            { month: "November", value: 173 },
        ],
        change: "0.5%",
        color: "primary",
        xaxis: "month",
    },
    {
        title: "GOOG",
        subtitle: "Alphabet Inc.",
        value: "$166,57",
        chartData: [
            { month: "January", value: 150 },
            { month: "February", value: 155 },
            { month: "March", value: 158 },
            { month: "April", value: 162 },
            { month: "May", value: 160 },
            { month: "June", value: 163 },
            { month: "July", value: 165 },
            { month: "August", value: 164 },
            { month: "September", value: 166 },
            { month: "October", value: 165 },
            { month: "November", value: 167 },
        ],
        change: "0.2%",
        color: "default",
        xaxis: "month",
    },
];

export const kpiStat8: KPIStat8Props[] = [
    {
        title: "Bounce Rate",
        value: "42.3%",
        chartData: [
            { month: "January", value: 18.2 },
            { month: "February", value: 22.1 },
            { month: "March", value: 37.8 },
            { month: "April", value: 53.5 },
            { month: "May", value: 65.8 },
            { month: "June", value: 71.2 },
            { month: "July", value: 62.8 },
            { month: "August", value: 52.3 },
            { month: "September", value: 51.8 },
            { month: "October", value: 50.3 },
            { month: "November", value: 51.1 },
            { month: "December", value: 40.5 },
        ],
        icon: Gauge,
        change: "-5.9%",
        color: "default",
        xaxis: "month",
    },
    {
        title: "Avg. Session Duration",
        value: "4:32",
        chartData: [
            { month: "January", value: 205 },
            { month: "February", value: 185 },
            { month: "March", value: 242 },
            { month: "April", value: 228 },
            { month: "May", value: 265 },
            { month: "June", value: 245 },
            { month: "July", value: 262 },
            { month: "August", value: 272 },
            { month: "September", value: 268 },
            { month: "October", value: 255 },
            { month: "November", value: 260 },
            { month: "December", value: 258 },
        ],
        icon: Clock,
        change: "+12.4%",
        color: "success",
        xaxis: "month",
    },
    {
        title: "Conversion Rate",
        value: "3.8%",
        chartData: [
            { month: "January", value: 2.1 },
            { month: "February", value: 2.4 },
            { month: "March", value: 3.2 },
            { month: "April", value: 2.8 },
            { month: "May", value: 3.5 },
            { month: "June", value: 3.2 },
            { month: "July", value: 3.6 },
            { month: "August", value: 3.8 },
        ],
        change: "+1.7%",
        color: "warning",
        icon: PieChart,
        xaxis: "month",
    },
    {
        title: "Pages per Session",
        value: 4.2,
        chartData: [
            { month: "Monday", value: 3.8 },
            { month: "Tuesday", value: 4.5 },
            { month: "Wednesday", value: 4.1 },
            { month: "Thursday", value: 3.9 },
            { month: "Friday", value: 4.3 },
            { month: "Saturday", value: 4.0 },
            { month: "Sunday", value: 4.2 },
        ],
        change: "+4.20",
        color: "primary",
        icon: Globe,
        xaxis: "day",
    },
    {
        title: "New vs Returning",
        value: "48.5%",
        chartData: [
            { month: "January", value: 72.4 },
            { month: "February", value: 74.2 },
            { month: "March", value: 71.5 },
            { month: "April", value: 69.8 },
            { month: "May", value: 70.1 },
            { month: "June", value: 68.9 },
            { month: "July", value: 67.8 },
            { month: "August", value: 68.5 },
        ],
        change: "-12.9%",
        color: "secondary",
        icon: MousePointer,
        xaxis: "month",
    },
    {
        title: "Load Time (ms)",
        value: "856ms",
        chartData: [
            { month: "January", value: 200 },
            { month: "February", value: 380 },
            { month: "March", value: 250 },
            { month: "April", value: 390 },
            { month: "May", value: 420 },
            { month: "June", value: 485 },
            { month: "July", value: 520 },
            { month: "August", value: 516 },
        ],
        change: "-28.7%",
        color: "danger",
        icon: Server,
        xaxis: "month",
    },
];

export const kpiStat7: KPIStat7Props[] = [
    {
        title: "Total Revenue",
        value: "$228k",
        change: "3%",
        changeType: "positive",
        trendChipPosition: "bottom",
        chartData: [
            { weekday: "Mo", value: 13200 },
            { weekday: "Tu", value: 8800 },
            { weekday: "We", value: 9441 },
            { weekday: "Th", value: 12300 },
            { weekday: "Fr", value: 16400 },
            { weekday: "Sa", value: 14000 },
            { weekday: "Su", value: 11300 },
        ],
    },
    {
        title: "Total Expenses",
        value: "$71.2k",
        change: "1%",
        changeType: "neutral",
        trendChipPosition: "bottom",
        chartData: [
            { weekday: "Mo", value: 5000 },
            { weekday: "Tu", value: 6200 },
            { weekday: "We", value: 9800 },
            { weekday: "Th", value: 5300 },
            { weekday: "Fr", value: 5700 },
            { weekday: "Sa", value: 6400 },
            { weekday: "Su", value: 8187 },
        ],
    },
    {
        title: "Total Profit",
        value: "$156k",
        change: "8%",
        changeType: "negative",
        trendChipPosition: "bottom",
        chartData: [
            { weekday: "Mo", value: 11500 },
            { weekday: "Tu", value: 7000 },
            { weekday: "We", value: 7641 },
            { weekday: "Th", value: 12700 },
            { weekday: "Fr", value: 13300 },
            { weekday: "Sa", value: 15600 },
            { weekday: "Su", value: 11813 },
        ],
    },
];

export const kpiStat6: KPIStat6Props[] = [
    {
        title: "New Subscriptions",
        value: 249,
        chartData: [
            {
                month: "January",
                value: 309,
            },
            {
                month: "February",
                value: 269,
            },
            {
                month: "March",
                value: 286,
            },
            {
                month: "April",
                value: 312,
            },
            {
                month: "May",
                value: 187,
            },
            {
                month: "June",
                value: 249,
            },
            {
                month: "July",
                value: 275,
            },
            {
                month: "August",
                value: 293,
            },
            {
                month: "September",
                value: 305,
            },
            {
                month: "October",
                value: 289,
            },
            {
                month: "November",
                value: 326,
            },
            {
                month: "December",
                value: 341,
            },
        ],
        change: "33%",
        changeType: "positive",
        xaxis: "month",
    },
    {
        title: "New Sales",
        value: 1159,
        chartData: [
            {
                month: "January",
                value: 40,
            },
            {
                month: "February",
                value: 1256,
            },
            {
                month: "March",
                value: 1123,
            },
            {
                month: "April",
                value: 1300,
            },
            {
                month: "May",
                value: 943,
            },
            {
                month: "June",
                value: 943,
            },
            {
                month: "July",
                value: 1089,
            },
            {
                month: "August",
                value: 1245,
            },
            {
                month: "September",
                value: 1190,
            },
            {
                month: "October",
                value: 1350,
            },
            {
                month: "November",
                value: 1159,
            },
            {
                month: "December",
                value: 1275,
            },
        ],
        change: "0%",
        changeType: "neutral",
        xaxis: "month",
    },
    {
        title: "Avg. Sale Revenue",
        value: "$328",
        chartData: [
            {
                month: "January",
                value: 40,
            },
            {
                month: "February",
                value: 8000,
            },
            {
                month: "March",
                value: 7000,
            },
            {
                month: "April",
                value: 15000,
            },
            {
                month: "May",
                value: 20000,
            },
            {
                month: "June",
                value: 18000,
            },
            {
                month: "July",
                value: 25000,
            },
            {
                month: "August",
                value: 50000,
            },
            {
                month: "September",
                value: 35000,
            },
            {
                month: "October",
                value: 28441,
            },
            {
                month: "November",
                value: 32000,
            },
            {
                month: "December",
                value: 30500,
            },
        ],
        change: "19%",
        changeType: "negative",
        xaxis: "month",
    },
];

export const kpiStat5: KPIStat5Props[] = [
    {
        title: "House Saving",
        value: 45300,
        maxValue: 150000,
        color: "warning",
        icon: Home,
    },
    {
        title: "Laptop",
        value: 300,
        maxValue: 1150,
        color: "secondary",
        icon: Laptop,
    },
    {
        title: "Trip Saving",
        value: 5300,
        maxValue: 15000,
        color: "default",
        icon: Palmtree,
    },
    {
        title: "Scooter Saving",
        value: 150,
        maxValue: 350,
        color: "primary",
        icon: Bike,
    },
];

export const kpiStat4: KPIStat4Props[] = [
    {
        title: "New Subscriptions",
        value: 249,
        chartData: [
            {
                month: "January",
                value: 159,
            },
            {
                month: "February",
                value: 269,
            },
            {
                month: "March",
                value: 286,
            },
            {
                month: "April",
                value: 312,
            },
            {
                month: "May",
                value: 287,
            },
            {
                month: "June",
                value: 249,
            },
            {
                month: "July",
                value: 275,
            },
            {
                month: "August",
                value: 293,
            },
            {
                month: "September",
                value: 305,
            },
            {
                month: "October",
                value: 289,
            },
            {
                month: "November",
                value: 266,
            },
            {
                month: "December",
                value: 278,
            },
        ],
        change: "33%",
        changeType: "positive",
        xaxis: "month",
    },
    {
        title: "New Customers",
        value: 1159,
        chartData: [
            {
                month: "January",
                value: 940,
            },
            {
                month: "February",
                value: 1256,
            },
            {
                month: "March",
                value: 1123,
            },
            {
                month: "April",
                value: 1300,
            },
            {
                month: "May",
                value: 1243,
            },
            {
                month: "June",
                value: 1113,
            },
            {
                month: "July",
                value: 1089,
            },
            {
                month: "August",
                value: 1245,
            },
            {
                month: "September",
                value: 1190,
            },
            {
                month: "October",
                value: 1159,
            },
            {
                month: "November",
                value: 1067,
            },
            {
                month: "December",
                value: 1198,
            },
        ],
        change: "0%",
        changeType: "neutral",
        xaxis: "month",
    },
    {
        title: "Month's Revenue",
        value: "$228,441",
        chartData: [
            {
                month: "January",
                value: 40000,
            },
            {
                month: "February",
                value: 48000,
            },
            {
                month: "March",
                value: 57000,
            },
            {
                month: "April",
                value: 65000,
            },
            {
                month: "May",
                value: 72000,
            },
            {
                month: "June",
                value: 88000,
            },
            {
                month: "July",
                value: 79000,
            },
            {
                month: "August",
                value: 95000,
            },
            {
                month: "September",
                value: 85000,
            },
            {
                month: "October",
                value: 84441,
            },
            {
                month: "November",
                value: 98000,
            },
            {
                month: "December",
                value: 79500,
            },
        ],
        change: "19%",
        changeType: "negative",
        xaxis: "month",
    },
    {
        title: "Todays' Sales",
        value: 54,
        chartData: [
            {
                month: "Monday",
                value: 38,
            },
            {
                month: "Tuesday",
                value: 40,
            },
            {
                month: "Wednesday",
                value: 37,
            },
            {
                month: "Thursday",
                value: 49,
            },
            {
                month: "Friday",
                value: 52,
            },
            {
                month: "June",
                value: 54,
            },
        ],
        change: "3.3%",
        changeType: "positive",
        xaxis: "day",
    },
];

export const graph1: Graph1Props[] = [
    {
        key: "unique-visitors",
        title: "Unique Visitors",
        suffix: "visitors",
        value: 147000,
        type: "number",
        change: "12.8%",
        changeType: "positive",
        chartData: [
            { month: "Jan", value: 98000 },
            { month: "Feb", value: 125000 },
            { month: "Mar", value: 89000 },
            { month: "Apr", value: 156000 },
            { month: "May", value: 112000 },
            { month: "Jun", value: 167000 },
            { month: "Jul", value: 138000 },
            { month: "Aug", value: 178000 },
            { month: "Sep", value: 129000 },
            { month: "Oct", value: 159000 },
            { month: "Nov", value: 147000 },
            { month: "Dec", value: 127000 },
        ],
    },
    {
        key: "total-visits",
        title: "Total Visits",
        suffix: "visits",
        value: 623000,
        type: "number",
        change: "-2.1%",
        changeType: "neutral",
        chartData: [
            { month: "Jan", value: 587000 },
            { month: "Feb", value: 698000 },
            { month: "Mar", value: 542000 },
            { month: "Apr", value: 728000 },
            { month: "May", value: 615000 },
            { month: "Jun", value: 689000 },
            { month: "Jul", value: 573000 },
            { month: "Aug", value: 695000 },
            { month: "Sep", value: 589000 },
            { month: "Oct", value: 652000 },
            { month: "Nov", value: 623000 },
            { month: "Dec", value: 523000 },
        ],
    },
    {
        key: "total-page-views",
        title: "Total Page Views",
        suffix: "views",
        value: 2312000,
        type: "number",
        change: "-5.7%",
        changeType: "negative",
        chartData: [
            { month: "Jan", value: 2820000 },
            { month: "Feb", value: 2380000 },
            { month: "Mar", value: 2690000 },
            { month: "Apr", value: 2145000 },
            { month: "May", value: 2760000 },
            { month: "Jun", value: 2280000 },
            { month: "Jul", value: 2620000 },
            { month: "Aug", value: 2145000 },
            { month: "Sep", value: 2470000 },
            { month: "Oct", value: 2230000 },
            { month: "Nov", value: 2312000 },
            { month: "Dec", value: 2230000 },
        ],
    },
    {
        key: "bounce-rate",
        title: "Bounce Rate",
        value: 36.78,
        suffix: "bounce rate",
        type: "percentage",
        change: "2.4%",
        changeType: "positive",
        chartData: [
            { month: "Jan", value: 42.82 },
            { month: "Feb", value: 35.95 },
            { month: "Mar", value: 39.25 },
            { month: "Apr", value: 34.58 },
            { month: "May", value: 40.92 },
            { month: "Jun", value: 35.15 },
            { month: "Jul", value: 38.75 },
            { month: "Aug", value: 33.95 },
            { month: "Sep", value: 39.65 },
            { month: "Oct", value: 35.85 },
            { month: "Nov", value: 36.78 },
            { month: "Dec", value: 34.78 },
        ],
    },
];

export const graph2: Graph2Props[] = [
    {
        key: "unique-visitors",
        title: "Unique Visitors",
        suffix: "visitors",
        value: 147000,
        type: "number",
        change: "12.8%",
        changeType: "positive",
        chartData: [
            { month: "Jan", value: 98000, lastYearValue: 43500 },
            { month: "Feb", value: 125000, lastYearValue: 38500 },
            { month: "Mar", value: 89000, lastYearValue: 58300 },
            { month: "Apr", value: 156000, lastYearValue: 35300 },
            { month: "May", value: 112000, lastYearValue: 89600 },
            { month: "Jun", value: 167000, lastYearValue: 56400 },
            { month: "Jul", value: 138000, lastYearValue: 45200 },
            { month: "Aug", value: 178000, lastYearValue: 84600 },
            { month: "Sep", value: 129000, lastYearValue: 73500 },
            { month: "Oct", value: 159000, lastYearValue: 65900 },
            { month: "Nov", value: 147000, lastYearValue: 82300 },
            { month: "Dec", value: 127000, lastYearValue: 95000 },
        ],
    },
    {
        key: "total-visits",
        title: "Total Visits",
        suffix: "visits",
        value: 623000,
        type: "number",
        change: "-2.1%",
        changeType: "neutral",
        chartData: [
            { month: "Jan", value: 587000, lastYearValue: 243500 },
            { month: "Feb", value: 698000, lastYearValue: 318500 },
            { month: "Mar", value: 542000, lastYearValue: 258300 },
            { month: "Apr", value: 728000, lastYearValue: 335300 },
            { month: "May", value: 615000, lastYearValue: 289600 },
            { month: "Jun", value: 689000, lastYearValue: 256400 },
            { month: "Jul", value: 573000, lastYearValue: 245200 },
            { month: "Aug", value: 695000, lastYearValue: 384600 },
            { month: "Sep", value: 589000, lastYearValue: 273500 },
            { month: "Oct", value: 652000, lastYearValue: 365900 },
            { month: "Nov", value: 623000, lastYearValue: 282300 },
            { month: "Dec", value: 523000, lastYearValue: 295000 },
        ],
    },
    {
        key: "total-page-views",
        title: "Total Page Views",
        suffix: "views",
        value: 2312000,
        type: "number",
        change: "-5.7%",
        changeType: "negative",
        chartData: [
            { month: "Jan", value: 2820000, lastYearValue: 1435000 },
            { month: "Feb", value: 2380000, lastYearValue: 1285000 },
            { month: "Mar", value: 2690000, lastYearValue: 1583000 },
            { month: "Apr", value: 2145000, lastYearValue: 1235000 },
            { month: "May", value: 2760000, lastYearValue: 1896000 },
            { month: "Jun", value: 2280000, lastYearValue: 1564000 },
            { month: "Jul", value: 2620000, lastYearValue: 1452000 },
            { month: "Aug", value: 2145000, lastYearValue: 1846000 },
            { month: "Sep", value: 2470000, lastYearValue: 1735000 },
            { month: "Oct", value: 2230000, lastYearValue: 1659000 },
            { month: "Nov", value: 2312000, lastYearValue: 1823000 },
            { month: "Dec", value: 2230000, lastYearValue: 1950000 },
        ],
    },
    {
        key: "bounce-rate",
        title: "Bounce Rate",
        value: 36.78,
        suffix: "bounce rate",
        type: "percentage",
        change: "2.4%",
        changeType: "positive",
        chartData: [
            { month: "Jan", value: 42.82, lastYearValue: 25.12 },
            { month: "Feb", value: 35.95, lastYearValue: 18.45 },
            { month: "Mar", value: 39.25, lastYearValue: 22.85 },
            { month: "Apr", value: 34.58, lastYearValue: 15.92 },
            { month: "May", value: 40.92, lastYearValue: 24.38 },
            { month: "Jun", value: 35.15, lastYearValue: 16.75 },
            { month: "Jul", value: 38.75, lastYearValue: 21.45 },
            { month: "Aug", value: 33.95, lastYearValue: 17.82 },
            { month: "Sep", value: 39.65, lastYearValue: 23.15 },
            { month: "Oct", value: 35.85, lastYearValue: 19.95 },
            { month: "Nov", value: 36.78, lastYearValue: 20.45 },
            { month: "Dec", value: 34.78, lastYearValue: 18.25 },
        ],
    },
];

export const circles4: Circles4Props[] = [
    {
        title: "Energy Activity",
        categories: ["Calories", "Steps", "Exercise"],
        color: "default",
        unit: "kcal",
        unitTitle: "Calories",
        total: 700,
        chartData: [
            { name: "Calories", value: 200, valueText: "1,623/2,000 kcal" },
            { name: "Steps", value: 350, valueText: "8,328/10,000 steps" },
            { name: "Exercise", value: 250, valueText: "25/120 min" },
        ],
    },
    {
        title: "Energy Activity",
        categories: ["Calories", "Steps", "Exercise"],
        color: "primary",
        unit: "kcal",
        unitTitle: "Calories",
        total: 700,
        chartData: [
            { name: "Calories", value: 200, valueText: "1,623/2,000 kcal" },
            { name: "Steps", value: 350, valueText: "8,328/10,000 steps" },
            { name: "Exercise", value: 250, valueText: "25/120 min" },
        ],
    },
    {
        title: "Energy Activity",
        categories: ["Calories", "Steps", "Exercise"],
        color: "secondary",
        unit: "kcal",
        unitTitle: "Calories",
        total: 700,
        chartData: [
            { name: "Calories", value: 200, valueText: "1,623/2,000 kcal" },
            { name: "Steps", value: 350, valueText: "8,328/10,000 steps" },
            { name: "Exercise", value: 250, valueText: "25/120 min" },
        ],
    },
    {
        title: "Energy Activity",
        categories: ["Calories", "Steps", "Exercise"],
        color: "success",
        unit: "kcal",
        unitTitle: "Calories",
        total: 700,
        chartData: [
            { name: "Calories", value: 200, valueText: "1,623/2,000 kcal" },
            { name: "Steps", value: 350, valueText: "8,328/10,000 steps" },
            { name: "Exercise", value: 250, valueText: "25/120 min" },
        ],
    },
    {
        title: "Energy Activity",
        categories: ["Calories", "Steps", "Exercise"],
        color: "warning",
        unit: "kcal",
        unitTitle: "Calories",
        total: 700,
        chartData: [
            { name: "Calories", value: 200, valueText: "1,623/2,000 kcal" },
            { name: "Steps", value: 350, valueText: "8,328/10,000 steps" },
            { name: "Exercise", value: 250, valueText: "25/120 min" },
        ],
    },
    {
        title: "Energy Activity",
        categories: ["Calories", "Steps", "Exercise"],
        color: "danger",
        unit: "kcal",
        unitTitle: "Calories",
        total: 700,
        chartData: [
            { name: "Calories", value: 200, valueText: "1,623/2,000 kcal" },
            { name: "Steps", value: 350, valueText: "8,328/10,000 steps" },
            { name: "Exercise", value: 250, valueText: "25/120 min" },
        ],
    },
];

export const bars1: Bars1Props[] = [
    {
        title: "Operating Systems",
        categories: ["Android", "iOS", "Web", "Windows"],
        color: "default",
        chartData: [
            {
                weekday: "Mon",
                android: 20,
                ios: 30,
                web: 20,
                windows: 10,
            },
            {
                weekday: "Tue",
                android: 35,
                ios: 35,
                web: 20,
                windows: 10,
            },
            {
                weekday: "Wed",
                android: 15,
                ios: 25,
                web: 20,
                windows: 10,
            },
            {
                weekday: "Thu",
                android: 12,
                ios: 35,
                web: 10,
                windows: 10,
            },
            {
                weekday: "Fri",
                android: 12,
                ios: 15,
                web: 20,
                windows: 10,
            },
            {
                weekday: "Sat",
                android: 35,
                ios: 25,
                web: 10,
                windows: 6,
            },
            {
                weekday: "Sun",
                android: 40,
                ios: 30,
                web: 20,
                windows: 10,
            },
        ],
    },
    {
        title: "Browser Usage",
        categories: ["Chrome", "Firefox", "Safari", "Edge"],
        color: "primary",
        chartData: [
            {
                weekday: "Mon",
                chrome: 45,
                firefox: 20,
                safari: 12,
                edge: 8,
            },
            {
                weekday: "Tue",
                chrome: 40,
                firefox: 10,
                safari: 12,
                edge: 8,
            },
            {
                weekday: "Wed",
                chrome: 52,
                firefox: 12,
                safari: 15,
                edge: 10,
            },
            {
                weekday: "Thu",
                chrome: 28,
                firefox: 12,
                safari: 12,
                edge: 8,
            },
            {
                weekday: "Fri",
                chrome: 30,
                firefox: 12,
                safari: 12,
                edge: 8,
            },
            {
                weekday: "Sat",
                chrome: 45,
                firefox: 32,
                safari: 8,
                edge: 5,
            },
            {
                weekday: "Sun",
                chrome: 68,
                firefox: 17,
                safari: 10,
                edge: 5,
            },
        ],
    },
    {
        title: "Device Types",
        categories: ["Mobile", "Tablet", "Desktop", "Other"],
        color: "secondary",
        chartData: [
            {
                weekday: "Mon",
                mobile: 25,
                tablet: 10,
                desktop: 20,
                other: 20,
            },
            {
                weekday: "Tue",
                mobile: 40,
                tablet: 10,
                desktop: 30,
                other: 20,
            },
            {
                weekday: "Wed",
                mobile: 10,
                tablet: 50,
                desktop: 20,
                other: 20,
            },
            {
                weekday: "Thu",
                mobile: 40,
                tablet: 20,
                desktop: 20,
                other: 10,
            },
            {
                weekday: "Fri",
                mobile: 15,
                tablet: 30,
                desktop: 20,
                other: 10,
            },
            {
                weekday: "Sat",
                mobile: 50,
                tablet: 20,
                desktop: 10,
                other: 20,
            },
            {
                weekday: "Sun",
                mobile: 50,
                tablet: 10,
                desktop: 20,
                other: 20,
            },
        ],
    },
];

export const bars2: Bars2Props[] = [
    {
        title: "Avg. Energy Activity",
        value: "580/280",
        unit: "kcal",
        categories: ["Low", "Medium", "High"],
        color: "warning",
        chartData: [
            {
                weekday: "Mon",
                Low: 120,
                Medium: 280,
                High: 180,
            },
            {
                weekday: "Tue",
                Low: 150,
                Medium: 320,
                High: 220,
            },
            {
                weekday: "Wed",
                Low: 180,
                Medium: 250,
                High: 150,
            },
            {
                weekday: "Thu",
                Low: 140,
                Medium: 290,
                High: 180,
            },
            {
                weekday: "Fri",
                Low: 160,
                Medium: 270,
                High: 190,
            },
            {
                weekday: "Sat",
                Low: 130,
                Medium: 240,
                High: 210,
            },
            {
                weekday: "Sun",
                Low: 170,
                Medium: 300,
                High: 240,
            },
        ],
    },
    {
        title: "Avg. Heart Rate",
        value: "72/52",
        unit: "bpm",
        categories: ["Low", "High"],
        color: "danger",
        chartData: [
            {
                weekday: "Mon",
                Low: 65,
                High: 85,
            },
            {
                weekday: "Tue",
                Low: 62,
                High: 82,
            },
            {
                weekday: "Wed",
                Low: 68,
                High: 88,
            },
            {
                weekday: "Thu",
                Low: 64,
                High: 84,
            },
            {
                weekday: "Fri",
                Low: 66,
                High: 86,
            },
            {
                weekday: "Sat",
                Low: 63,
                High: 83,
            },
            {
                weekday: "Sun",
                Low: 67,
                High: 87,
            },
        ],
    },
    {
        title: "Avg. Daily Steps",
        value: "8,432",
        unit: "steps",
        categories: ["Low", "Medium", "High"],
        color: "success",
        chartData: [
            {
                weekday: "Mon",
                Low: 2500,
                Medium: 4000,
                High: 6500,
            },
            {
                weekday: "Tue",
                Low: 3000,
                Medium: 4500,
                High: 7000,
            },
            {
                weekday: "Wed",
                Low: 2800,
                Medium: 4200,
                High: 6800,
            },
            {
                weekday: "Thu",
                Low: 3200,
                Medium: 4800,
                High: 7200,
            },
            {
                weekday: "Fri",
                Low: 2700,
                Medium: 4100,
                High: 6400,
            },
            {
                weekday: "Sat",
                Low: 2000,
                Medium: 3500,
                High: 5500,
            },
            {
                weekday: "Sun",
                Low: 1800,
                Medium: 3200,
                High: 5000,
            },
        ],
    },
];

export const bars3: Bars3Props[] = [
    {
        title: "Monthly Expenses",
        value: "$5,420",
        unit: "avg",
        categories: ["Expenses", "Savings"],
        color: "default",
        chartData: [
            {
                month: "Jan",
                Expenses: 1340,
                Savings: -1340,
            },
            {
                month: "Feb",
                Expenses: 450,
                Savings: -750,
            },
            {
                month: "Mar",
                Expenses: 1044,
                Savings: -1044,
            },
            {
                month: "Apr",
                Expenses: 450,
                Savings: -450,
            },
            {
                month: "May",
                Expenses: 900,
                Savings: -700,
            },
            {
                month: "Jun",
                Expenses: 1250,
                Savings: -1250,
            },
            {
                month: "Jul",
                Expenses: 400,
                Savings: -600,
            },
            {
                month: "Aug",
                Expenses: 600,
                Savings: -800,
            },
            {
                month: "Sep",
                Expenses: 1200,
                Savings: -1200,
            },
            {
                month: "Oct",
                Expenses: 500,
                Savings: -500,
            },
            {
                month: "Nov",
                Expenses: 800,
                Savings: -800,
            },
        ],
    },
    {
        title: "Annual Revenue",
        value: "$12,780",
        unit: "avg",
        categories: ["Revenue", "Costs"],
        color: "secondary",
        chartData: [
            {
                month: "Jan",
                Revenue: 1340,
                Costs: -1340,
            },
            {
                month: "Feb",
                Revenue: 450,
                Costs: -750,
            },
            {
                month: "Mar",
                Revenue: 1044,
                Costs: -1044,
            },
            {
                month: "Apr",
                Revenue: 450,
                Costs: -450,
            },
            {
                month: "May",
                Revenue: 900,
                Costs: -700,
            },
            {
                month: "Jun",
                Revenue: 1250,
                Costs: -1250,
            },
            {
                month: "Jul",
                Revenue: 400,
                Costs: -600,
            },
            {
                month: "Aug",
                Revenue: 600,
                Costs: -800,
            },
            {
                month: "Sep",
                Revenue: 1200,
                Costs: -1200,
            },
            {
                month: "Oct",
                Revenue: 500,
                Costs: -500,
            },
            {
                month: "Nov",
                Revenue: 800,
                Costs: -800,
            },
        ],
    },
    {
        title: "Project Budget",
        value: "$8,350",
        unit: "total",
        categories: ["Budget", "Spent"],
        color: "warning",
        chartData: [
            {
                month: "Jan",
                Budget: 1340,
                Spent: -1340,
            },
            {
                month: "Feb",
                Budget: 450,
                Spent: -750,
            },
            {
                month: "Mar",
                Budget: 1044,
                Spent: -1044,
            },
            {
                month: "Apr",
                Budget: 450,
                Spent: -450,
            },
            {
                month: "May",
                Budget: 900,
                Spent: -700,
            },
            {
                month: "Jun",
                Budget: 1250,
                Spent: -1250,
            },
            {
                month: "Jul",
                Budget: 400,
                Spent: -600,
            },
            {
                month: "Aug",
                Budget: 600,
                Spent: -800,
            },
            {
                month: "Sep",
                Budget: 1200,
                Spent: -1200,
            },
            {
                month: "Oct",
                Budget: 500,
                Spent: -500,
            },
            {
                month: "Nov",
                Budget: 800,
                Spent: -800,
            },
        ],
    },
];

export const bars4: Bars4Props[] = [
    {
        title: "Avg. Energy Activity",
        value: "580/280",
        unit: "kcal",
        categories: ["Low", "Medium", "High"],
        color: "default",
        chartData: [
            {
                weekday: "Mon",
                Low: 120,
                Medium: 280,
                High: 180,
            },
            {
                weekday: "Tue",
                Low: 150,
                Medium: 320,
                High: 220,
            },
            {
                weekday: "Wed",
                Low: 180,
                Medium: 250,
                High: 150,
            },
            {
                weekday: "Thu",
                Low: 140,
                Medium: 290,
                High: 180,
            },
            {
                weekday: "Fri",
                Low: 160,
                Medium: 270,
                High: 190,
            },
            {
                weekday: "Sat",
                Low: 130,
                Medium: 240,
                High: 210,
            },
            {
                weekday: "Sun",
                Low: 170,
                Medium: 300,
                High: 240,
            },
        ],
    },
    {
        title: "Avg. Heart Rate",
        value: "72/52",
        unit: "bpm",
        categories: ["Low", "High"],
        color: "primary",
        chartData: [
            {
                weekday: "Mon",
                Low: 65,
                High: 85,
            },
            {
                weekday: "Tue",
                Low: 62,
                High: 82,
            },
            {
                weekday: "Wed",
                Low: 68,
                High: 88,
            },
            {
                weekday: "Thu",
                Low: 64,
                High: 84,
            },
            {
                weekday: "Fri",
                Low: 66,
                High: 86,
            },
            {
                weekday: "Sat",
                Low: 63,
                High: 83,
            },
            {
                weekday: "Sun",
                Low: 57,
                High: 64,
            },
        ],
    },
    {
        title: "Avg. Daily Steps",
        value: "8,432",
        unit: "steps",
        categories: ["Low", "Medium", "High"],
        color: "secondary",
        chartData: [
            {
                weekday: "Mon",
                Low: 2500,
                Medium: 4000,
                High: 6500,
            },
            {
                weekday: "Tue",
                Low: 3000,
                Medium: 4500,
                High: 7000,
            },
            {
                weekday: "Wed",
                Low: 2800,
                Medium: 4200,
                High: 6800,
            },
            {
                weekday: "Thu",
                Low: 3200,
                Medium: 4800,
                High: 7200,
            },
            {
                weekday: "Fri",
                Low: 2700,
                Medium: 4100,
                High: 6400,
            },
            {
                weekday: "Sat",
                Low: 2000,
                Medium: 3500,
                High: 5500,
            },
            {
                weekday: "Sun",
                Low: 2400,
                Medium: 3200,
                High: 5000,
            },
        ],
    },
];

export const circles1: Circles1Props[] = [
    {
        title: "Personal Expenses",
        value: "$5,420",
        unit: "avg.",
        changePercentage: 24.8,
        changeType: "positive",
        categories: ["Delivery", "Social", "Shopping", "Food"],
        color: "default",
        chartData: [
            { name: "Delivery", value: 400 },
            { name: "Social", value: 300 },
            { name: "Shopping", value: 300 },
            { name: "Food", value: 200 },
        ],
    },
    {
        title: "Summary Expenses",
        value: "$12,345",
        unit: "total",
        changePercentage: 15.2,
        changeType: "positive",
        categories: ["Sales", "Marketing", "Support", "Dev"],
        color: "primary",
        chartData: [
            { name: "Sales", value: 450 },
            { name: "Marketing", value: 300 },
            { name: "Support", value: 250 },
            { name: "Dev", value: 200 },
        ],
    },
    {
        title: "Cost Distribution",
        value: "$8,790",
        unit: "total",
        changePercentage: -5.4,
        changeType: "negative",
        categories: ["Operations", "Personnel", "Tools", "Office"],
        color: "secondary",
        chartData: [
            { name: "Operations", value: 350 },
            { name: "Personnel", value: 280 },
            { name: "Tools", value: 220 },
            { name: "Office", value: 150 },
        ],
    },
];

export const circles2: Circles2Props[] = [
    {
        title: "Traffic Sources",
        total: 224000,
        unit: "Visitors",
        categories: ["Search", "Direct", "Social", "Referral"],
        color: "default",
        chartData: [
            { name: "Search", value: 400 },
            { name: "Direct", value: 300 },
            { name: "Social", value: 300 },
            { name: "Referral", value: 200 },
        ],
    },
    {
        title: "Device Usage",
        total: 4500,
        unit: "Devices",
        categories: ["Mobile", "Desktop", "Tablet", "Smart TV"],
        color: "primary",
        chartData: [
            { name: "Mobile", value: 450 },
            { name: "Desktop", value: 300 },
            { name: "Tablet", value: 250 },
            { name: "Smart TV", value: 200 },
        ],
    },
    {
        title: "Browser Usage",
        total: 8790,
        unit: "Devices",
        categories: ["Chrome", "Safari", "Firefox", "Edge"],
        color: "secondary",
        chartData: [
            { name: "Chrome", value: 350 },
            { name: "Safari", value: 280 },
            { name: "Firefox", value: 220 },
            { name: "Edge", value: 150 },
        ],
    },
];